// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPp5-fEmWXmJz2cFVxyXdZeFPiGiN70PE',
    appId: '1:483409885225:web:45bd9b4111fcb2a591c438',
    messagingSenderId: '483409885225',
    projectId: 'meetbank-42b78',
    authDomain: 'meetbank-42b78.firebaseapp.com',
    storageBucket: 'meetbank-42b78.firebasestorage.app',
    measurementId: 'G-M044Q0S9RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKq6x2vtFL1lQ3nlF0fz5tt9urcGuf1hU',
    appId: '1:483409885225:android:d3b879461677acd291c438',
    messagingSenderId: '483409885225',
    projectId: 'meetbank-42b78',
    storageBucket: 'meetbank-42b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZsHfg6Uzl_8MvGalsxfsdAHdOQGUI8fI',
    appId: '1:483409885225:ios:68a86904586f09b591c438',
    messagingSenderId: '483409885225',
    projectId: 'meetbank-42b78',
    storageBucket: 'meetbank-42b78.firebasestorage.app',
    androidClientId: '483409885225-s8aeosd5rlg1fsv5ilpqcfli58jb425m.apps.googleusercontent.com',
    iosClientId: '483409885225-9buqf4gcv9o39d9vss6jvoscppkq2e8p.apps.googleusercontent.com',
    iosBundleId: 'com.wib.meetbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZsHfg6Uzl_8MvGalsxfsdAHdOQGUI8fI',
    appId: '1:483409885225:ios:68a86904586f09b591c438',
    messagingSenderId: '483409885225',
    projectId: 'meetbank-42b78',
    storageBucket: 'meetbank-42b78.firebasestorage.app',
    androidClientId: '483409885225-s8aeosd5rlg1fsv5ilpqcfli58jb425m.apps.googleusercontent.com',
    iosClientId: '483409885225-9buqf4gcv9o39d9vss6jvoscppkq2e8p.apps.googleusercontent.com',
    iosBundleId: 'com.wib.meetbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPp5-fEmWXmJz2cFVxyXdZeFPiGiN70PE',
    appId: '1:483409885225:web:45bd9b4111fcb2a591c438',
    messagingSenderId: '483409885225',
    projectId: 'meetbank-42b78',
    authDomain: 'meetbank-42b78.firebaseapp.com',
    storageBucket: 'meetbank-42b78.firebasestorage.app',
    measurementId: 'G-M044Q0S9RY',
  );

}